{% raw -%}
#!/usr/bin/env just --justfile

#export PATH := join(justfile_directory(), "node_modules", "bin") + ":" + env_var('PATH')

#build:
#  npm run build

unexport OPENAI_API_KEY

_default:
    just --list

dev:
    pnpm dev

{%- endraw %}