name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Compile with tsc
        run: pnpm tsc
