{% raw -%}

name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: machinehead/cicd/.github/workflows/typescript-ci.yml@main
    with:
      node-version: '23'
    secrets:
      token: ${{ secrets.SUBMODULE_PAT }}
      DOTENVENC_PASS: ${{ secrets.DOTENVENC_PASS }}

{%- endraw %}